### ISSUE TITLE
Can users use any form of payment?

### ISSUE THREAD

**Issue by DrDBanner** [SwarmCitySupport/FAQ#2]
> No 

That is more or less not accurate. Technicall yes. You are right. But there will be a background token exchange system, so that you can pay in $ or whatever and this will be transparently converted in SWT in the background. You recieve your payments in SWT and have the option to cashout in any currency that is supported within the app or any official exchange is offering. 

I think this answer should be polished as it might look scary at first.

**Comment by QueenBeeSC** [comment]
check now I updated it, thanks for pointing that out. It could cause concern to think only crypto savvy people could enter the ecosystem
