### ISSUE TITLE
Questions in table have no anchor

### ISSUE THREAD

**Issue by DrDBanner** [SwarmCitySupport/FAQ#3]
If you make your questions a h4 or h5 your are able to link to them directly.

**Comment by QueenBeeSC** [comment]
I don't understand this...are the links dead or missing all together...?

**Comment by DrDBanner** [comment]
No. Each question is not a heading. It is pure Text in bold. Write 4 or 5 Hashtags in a row before them and they turn into a heading and get automatically an anchor. That way you can link externally to each question individually.
