### ISSUE TITLE
SWT withdrawal

### ISSUE THREAD

**Issue by LeanPulseLabs** [SwarmCitySupport/FAQ#5]
I enter the correct Bittrex address, but keep getting the following message "Something went wrong, try again." when I try to withdraw SWT from the https://swarm.city wallet. I've tried the withdrawal 5 times and verified the Bittrex, but continue to get the same message.

**Comment by QueenBeeSC** [comment]
Hello,

Thanks for reaching out and
I'm sorry you're having this issue.

It appears to me that you just need to add a small amount of ether into
your SWT wallet.

To do this, login and click on your nickname to display and copy your
public address and send about .01 ether to cover the gas transaction fees.
This should be more than enough to cover a few transactions.

**Comment by LeanPulseLabs** [comment]
I tried that and it works now. thank you.
